name: Automatic Build Script

on:
  schedule:
    - cron: "0 0 1,15 * *"
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y aria2 \
            build-essential \
            scons \
            pkg-config \
            libz-dev \
            libpng-dev \
            libjpeg-dev \
            libfreetype6-dev \
            liblua5.1-0-dev \
            gettext

      - name: Clone NSIS source
        run: |
          git clone https://github.com/NSIS-Dev/nsis.git
          cd nsis
          scons SKIPZLIB=1 ZLIB_W32= SKIPWIN32=1

      - name: Install NSIS
        run: |
          cd nsis
          sudo scons install PREFIX=/usr/local

      - name: Run generate.sh
        run: |
          chmod +x ./generate_all.sh
          ./generate_all.sh

      - name: Get build date
        id: date
        run: echo "date=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.date.outputs.date }}
          name: Release ${{ steps.date.outputs.date }}
          body: |
            MSVC Offline Installer build automatically generated on ${{ steps.date.outputs.date }}. It does not include DirectX installation.

            [You can download DirectX Redistributable from here.](https://download.microsoft.com/download/8/4/a/84a35bf1-dafe-4ae8-82af-ad2ae20b6b14/directx_jun2010_redist.exe)

            AllOS variant: Supports at least Windows XP.
            Win7 variant: Supports at least Windows 7.
            Win10_11 variant: Supports at least Windows 10.

            Following Redistributable Runtime will be installed:
            Windows XP: 14.28.29213.0 (2015-2019)
            Windows Vista: 14.32.31332.0 (2015-2022)
            Windows 7, 8, 8.1: 14.44.35211.0 (2015-2022)
            Windows 10, 11: Latest Version when this build is released (2015-2026)
          files: MSVC_Offline_Setup_*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
